#!/usr/bin/env python

import os, json, sys

PWD = os.path.abspath(os.path.dirname(__file__))
DST = os.path.join(PWD, '../src/main/resources/com/squarespace/less/match')

hx = lambda n: '%02x' % n
hx1 = lambda n: '%x' % n

# converted colors from: https://www.w3.org/TR/css-color-4/
#
# note: 'rebeccapurple' is IE11+ only so we omit it for now

SKIP = set(['rebeccapurple'])

def from_hex(s):
    return [int(c, 16) for c in (s[1:3], s[3:5], s[5:7])]

def convert(r, g, b):
    # 6-digit form
    r, g, b = [int(c) for c in (r, g, b)]
    c = '#%02x%02x%02x' % (r, g, b)
    cols = [c]

    # some colors can also have compact forms
    r0 = r & 0xf
    r1 = (r >> 4) & 0xf
    g0 = g & 0xf
    g1 = (g >> 4) & 0xf
    b0 = b & 0xf
    b1 = (b >> 4) & 0xf
    if r0 == r1 and g0 == g1 and b0 == b1:
        c = '#%x%x%x' % (r0, g0, b0)
        cols.append(c)
    return cols

def main():
    s = ''

    seen = set()

    # index all colors by name
    for line in open('named-colors.txt'):
        line = line.strip()
        if not line:
            continue

        name, _, r, g, b = line.split()
        if name in SKIP:
            continue

        k = (r, g, b)

        for c in convert(r, g, b):
            s += '%s\t%s\n' % (c, name)
            seen.add(c)

    # merge in the scraped colors, which occurred 50 or more times
    # over 100k+ sites
    for line in open('scraped-colors.txt'):
        r, g, b = from_hex(line.rstrip().lower())
        for c in convert(r, g, b):
            if c not in seen:
                s += '%s\n' % c

    out = open(os.path.join(DST, 'colors.txt'), 'w')
    out.write(s)
    out.close()

if __name__ == '__main__':
    main()

